function [LHS,ll_col,rx_col,MM_col,G_col]=L_FD_LHS(settings)
    % LHS Matrix for Operator (-L) for solving f(e)
    %% Gyrotactic Term
    MM=transpose(spdiags([-sin(settings.theta)/(2*settings.dtheta)...
        -2*cos(settings.theta) sin(settings.theta)/(2*settings.dtheta)],...
        -1:1,settings.n_theta,settings.n_theta));

    MM_col=settings.beta*kron(MM,speye(settings.n_phi,settings.n_phi));
    
    %% Vorticity Term
    cot_term=[0;cot(settings.theta(2:(settings.n_theta-1)));0];
    
    d1phicos_wide=spdiags(cos(settings.phi')*[-1/60 3/20 -3/4 0 3/4 -3/20 1/60],0:6,settings.n_phi,settings.n_phi+6); %Central Difference 6th order in phi
    d1phicos=d1phicos_wide(:,3+(1:settings.n_phi));
    d1phicos(1:3,end-2:end)=d1phicos(1:3,end-2:end)+d1phicos_wide(1:3,1:3);
    d1phicos(end-2:end,1:3)=d1phicos(end-2:end,1:3)+d1phicos_wide(end-2:end,end-2:end);
    d1phicos2_wide=spdiags(cos(2*settings.phi')*[-1/60 3/20 -3/4 0 3/4 -3/20 1/60],0:6,settings.n_phi,settings.n_phi+6); %Central Difference 6th order in phi
    d1phicos2=d1phicos2_wide(:,3+(1:settings.n_phi));
    d1phicos2(1:3,end-2:end)=d1phicos2(1:3,end-2:end)+d1phicos2_wide(1:3,1:3);
    d1phicos2(end-2:end,1:3)=d1phicos2(end-2:end,1:3)+d1phicos2_wide(end-2:end,end-2:end);
    G_front_col_e1=-settings.omega1/2*...
        kron(spdiags(cot_term,0,settings.n_theta,settings.n_theta)...
        ,d1phicos/(settings.dphi));
    
    d1phi_wide=spdiags(ones(settings.n_phi,1)*[-1/60 3/20 -3/4 0 3/4 -3/20 1/60],0:6,settings.n_phi,settings.n_phi+6); %Central Difference 6th order in phi
    d1phi=d1phi_wide(:,3+(1:settings.n_phi));
    d1phi(1:3,end-2:end)=d1phi(1:3,end-2:end)+d1phi_wide(1:3,1:3);
    d1phi(end-2:end,1:3)=d1phi(end-2:end,1:3)+d1phi_wide(end-2:end,end-2:end);
    G_front_col_e3=settings.omega3/2*...
        kron(speye(settings.n_theta,settings.n_theta)...
        ,d1phi/settings.dphi);
    
    d1phisin_wide=spdiags(sin(settings.phi')*[-1/60 3/20 -3/4 0 3/4 -3/20 1/60],0:6,settings.n_phi,settings.n_phi+6); %Central Difference 6th order in phi
    d1phisin=d1phisin_wide(:,3+(1:settings.n_phi));
    d1phisin(1:3,end-2:end)=d1phisin(1:3,end-2:end)+d1phisin_wide(1:3,1:3);
    d1phisin(end-2:end,1:3)=d1phisin(end-2:end,1:3)+d1phisin_wide(end-2:end,end-2:end);
    d1phisin2_wide=spdiags(sin(2*settings.phi')*[-1/60 3/20 -3/4 0 3/4 -3/20 1/60],0:6,settings.n_phi,settings.n_phi+6); %Central Difference 6th order in phi
    d1phisin2=d1phisin2_wide(:,3+(1:settings.n_phi));
    d1phisin2(1:3,end-2:end)=d1phisin2(1:3,end-2:end)+d1phisin2_wide(1:3,1:3);
    d1phisin2(end-2:end,1:3)=d1phisin2(end-2:end,1:3)+d1phisin2_wide(end-2:end,end-2:end);
    G_front_col_e2=-settings.omega2/2*...
        kron(spdiags(cot_term,0,settings.n_theta,settings.n_theta)...
        ,d1phisin/(settings.dphi));
    
    
    G_back_col_e1=-settings.omega1/2*...
        kron(spdiags(ones(settings.n_theta,1)*[-1 1],[-1 1],settings.n_theta,settings.n_theta)/...
        (2*settings.dtheta),spdiags(sin(settings.phi'),0,settings.n_phi,settings.n_phi));
    G_back_col_e2=settings.omega2/2*...
        kron(spdiags(ones(settings.n_theta,1)*[-1 1],[-1 1],settings.n_theta,settings.n_theta)/...
        (2*settings.dtheta),spdiags(cos(settings.phi'),0,settings.n_phi,settings.n_phi));
    
    G_col=G_front_col_e1+G_front_col_e2+G_front_col_e3+G_back_col_e1+G_back_col_e2;
    
    E_front_col_E13=-settings.E13*...
        kron(spdiags(cot_term,0,settings.n_theta,settings.n_theta)...
        ,d1phisin/(settings.dphi));
    E_back_col_E13=settings.E13*...
        kron(diag(cos(2*settings.theta))*spdiags(ones(settings.n_theta,1)*[-1 1],[-1 1],settings.n_theta,settings.n_theta)/...
        (2*settings.dtheta),spdiags(cos(settings.phi'),0,settings.n_phi,settings.n_phi));
    E_mid_col_E13=-3*settings.E13*...
        kron(diag(sin(2*settings.theta))...
        ,spdiags(cos(settings.phi'),0,settings.n_phi,settings.n_phi));
    
    E_front_col_E23=settings.E23*...
        kron(spdiags(cot_term,0,settings.n_theta,settings.n_theta)...
        ,d1phicos/(settings.dphi));
    E_back_col_E23=settings.E23*...
        kron(diag(cos(2*settings.theta))*spdiags(ones(settings.n_theta,1)*[-1 1],[-1 1],settings.n_theta,settings.n_theta)/...
        (2*settings.dtheta),spdiags(sin(settings.phi'),0,settings.n_phi,settings.n_phi));
    E_mid_col_E23=-3*settings.E23*...
        kron(diag(sin(2*settings.theta))...
        ,spdiags(sin(settings.phi'),0,settings.n_phi,settings.n_phi));
    
    E_front_col_E12=settings.E12*...
        kron(speye(settings.n_theta,settings.n_theta)...
        ,d1phicos2/(settings.dphi));
    E_back_col_E12=settings.E12/2*...
        kron(diag(sin(2*settings.theta))*spdiags(ones(settings.n_theta,1)*[-1 1],[-1 1],settings.n_theta,settings.n_theta)/...
        (2*settings.dtheta),spdiags(sin(2*settings.phi'),0,settings.n_phi,settings.n_phi));
    E_mid_col_E12=-3*settings.E12*...
        kron(diag(sin(settings.theta).^2)...
        ,spdiags(sin(2*settings.phi'),0,settings.n_phi,settings.n_phi));
    
    E_E11mE22=(settings.E11-settings.E22)*(...
        (-3/2)*(kron(diag(sin(settings.theta).^2)...
        ,spdiags(cos(2*settings.phi'),0,settings.n_phi,settings.n_phi)))...
        -(1/2)*kron(speye(settings.n_theta,settings.n_theta)...
        ,d1phisin2/(settings.dphi))...
        +(1/4)*kron(diag(sin(2*settings.theta))*spdiags(ones(settings.n_theta,1)*[-1 1],[-1 1],settings.n_theta,settings.n_theta)/...
        (2*settings.dtheta),spdiags(cos(2*settings.phi'),0,settings.n_phi,settings.n_phi)));
    
    E_Ediag=(settings.E11+settings.E22-2*settings.E33)/4*(...
        speye(settings.n_phi*settings.n_theta)...
        +3*kron(diag(cos(2*settings.theta)),speye(settings.n_phi))...
        +kron(diag(sin(2*settings.theta))*spdiags(ones(settings.n_theta,1)*[-1 1],[-1 1],settings.n_theta,settings.n_theta)/(2*settings.dtheta)...
        ,speye(settings.n_phi)));
        
    E_col=E_front_col_E13+E_back_col_E13+E_mid_col_E13...
         +E_front_col_E12+E_back_col_E12+E_mid_col_E12...
         +E_front_col_E23+E_back_col_E23+E_mid_col_E23...
         +E_E11mE22+E_Ediag;
    %% Combined Advection Term
    rx_col=MM_col+G_col+settings.B*E_col;

    %% Diffusive (Laplacian) Term
    pre_ll=transpose(...
        spdiags(...
        [cot_term/...
        (2*settings.dtheta)+settings.dtheta^(-2) ...
        -2*settings.dtheta^(-2)*ones(settings.n_theta,1) ...
        -cot_term/(2*settings.dtheta)+settings.dtheta^(-2)]...
        ,-1:1,settings.n_theta,settings.n_theta));
    ll_col=kron(pre_ll,speye(settings.n_phi,settings.n_phi));
    
    sin2_term=[0;sin(settings.theta(2:(settings.n_theta-1))).^(-2);0];
    d2phi_wide=spdiags(ones(settings.n_phi,1)*[1/90 -3/20 3/2 -49/18 3/2 -3/20 1/90],0:6,settings.n_phi,settings.n_phi+6);
    d2phi=d2phi_wide(:,3+(1:settings.n_phi));
    d2phi(1:3,end-2:end)=d2phi(1:3,end-2:end)+d2phi_wide(1:3,1:3);
    d2phi(end-2:end,1:3)=d2phi(end-2:end,1:3)+d2phi_wide(end-2:end,end-2:end);
    
    ll_col=ll_col+...
        kron(spdiags(sin2_term,0,settings.n_theta,settings.n_theta),...
        d2phi)*settings.dphi^(-2);
    
    %% All Combined Term (-L), which can be directly used for timestepping
    LHS=ll_col-rx_col;

end